### ISSUE TITLE
As a visitor of the website, I have a video playing as header.

### ISSUE THREAD

**Issue by DarkoBoesmans** [BloatedVirus/projectp-frontend#1]
**Description**
background video on the home page when the user is on the homepage

**Sources**
- https://www.w3schools.com/howto/howto_css_fullscreen_video.asp
- https://stackoverflow.com/questions/20818881/use-video-as-background-for-div
- https://www.youtube.com/watch?v=LSRNmhLS76o

**Comment by RobinDeCroock** [comment]
**Desccription**
background video on home page when user is on homepage

**Sources**
https://docs.github.com/en/github-ae@latest/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards
